# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json

blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/kirkpatrickprice/analysis-toolkit/blob/main/README.md
    about: Check the documentation for usage examples and troubleshooting
  - name: 💬 Discussions
    url: https://github.com/kirkpatrickprice/analysis-toolkit/discussions
    about: Ask questions, share ideas, or discuss the project with the community
