# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json

blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://github.com/kirkpatrickprice/analysis-toolkit/blob/main/README.md
    about: Check the documentation for usage examples and troubleshooting
