name: Security Vulnerability Report
description: Report security vulnerabilities in dependencies or the toolkit
title: "[SECURITY] "
labels: ["security", "vulnerability", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        🔒 **Security Notice**: This template is for reporting security vulnerabilities. 
        
        **For critical vulnerabilities**, please use GitHub's [Security Advisory](https://github.com/your-org/analysis-toolkit/security/advisories/new) feature instead of creating a public issue.
        
        This template focuses on dependency vulnerabilities since the toolkit runs locally and processes user data.

  - type: dropdown
    id: vulnerability_type
    attributes:
      label: Vulnerability Type
      description: What type of security vulnerability is this?
      options:
        - Dependency Vulnerability - Known CVE in a package dependency
        - Dependency Vulnerability - Potential security issue in dependency
        - Supply Chain - Compromised or suspicious package
        - Data Exposure - Toolkit exposes sensitive data inappropriately
        - Input Validation - Malicious input could cause issues
        - File System - Unsafe file operations
        - Other Security Concern
    validations:
      required: true

  - type: input
    id: affected_package
    attributes:
      label: Affected Package/Dependency
      description: "For dependency issues: Which package is affected?"
      placeholder: "e.g., pandas==2.1.0, openpyxl==3.1.2, or 'multiple packages'"

  - type: input
    id: cve_id
    attributes:
      label: CVE ID or Security Advisory
      description: If there's a known CVE or security advisory, provide the ID
      placeholder: "e.g., CVE-2024-12345, GHSA-xxxx-xxxx-xxxx, or link to advisory"

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Critical - Immediate action required
        - High - Significant security risk
        - Medium - Moderate security risk
        - Low - Minor security concern
        - Unknown - Need help assessing severity
    validations:
      required: true

  - type: dropdown
    id: affected_versions
    attributes:
      label: Affected Toolkit Versions
      description: Which versions of the analysis toolkit are affected?
      options:
        - Latest version only
        - Multiple recent versions
        - All versions
        - Specific version (specify in description)
        - Unknown - need help determining
    validations:
      required: true

  - type: textarea
    id: vulnerability_description
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability and its potential impact
      placeholder: |
        - What is the vulnerability?
        - How could it be exploited?
        - What data or systems could be affected?
        - What are the potential consequences?
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Reproduction Steps (if applicable)
      description: How can this vulnerability be demonstrated? (Only provide safe reproduction steps)
      placeholder: |
        1. Install specific package version...
        2. Run specific command...
        3. Observe security issue...
        
        Note: Only provide steps that are safe to execute

  - type: textarea
    id: affected_functionality
    attributes:
      label: Affected Functionality
      description: Which parts of the toolkit are affected by this vulnerability?
      placeholder: |
        - Specific commands or modules affected
        - Data processing features impacted
        - File operations that might be vulnerable
        - Excel export functionality
        - Input parsing (RTF, CSV, etc.)

  - type: dropdown
    id: data_at_risk
    attributes:
      label: Data at Risk
      description: What type of data could be exposed or compromised?
      options:
        - Input files being processed
        - Generated reports/Excel files
        - Temporary files
        - System files
        - Network data (if applicable)
        - No data exposure
        - Unknown
    validations:
      required: true

  - type: textarea
    id: scanner_output
    attributes:
      label: Security Scanner Output
      description: If you used a security scanner (pip-audit, safety, etc.), paste the relevant output
      placeholder: |
        Example from pip-audit:
        Found 2 known vulnerabilities in 1 package
        Package: requests
        Installed: 2.25.1
        Fixed: 2.31.0
        ID: GHSA-j8r2-6x86-q33q
      render: shell

  - type: textarea
    id: mitigation_suggestions
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for fixing or mitigating this vulnerability?
      placeholder: |
        - Update package to version X.X.X
        - Pin package to safe version
        - Replace package with alternative
        - Add input validation
        - Configuration changes needed

  - type: dropdown
    id: workaround_available
    attributes:
      label: Workaround Available
      description: Is there a workaround to avoid this vulnerability?
      options:
        - Yes - workaround described below
        - Partial workaround available
        - No known workaround
        - Unknown
    validations:
      required: true

  - type: textarea
    id: workaround_description
    attributes:
      label: Workaround Description
      description: If a workaround exists, describe how users can protect themselves
      placeholder: |
        - Specific commands to avoid
        - Alternative packages to use
        - Configuration changes
        - Additional validation steps

  - type: dropdown
    id: discovery_method
    attributes:
      label: How was this discovered?
      description: How did you discover this vulnerability?
      options:
        - Security scanner (pip-audit, safety, etc.)
        - GitHub Security Advisory
        - Package maintainer notification
        - CVE database
        - Manual code review
        - User report
        - Other automated tool
        - Research/investigation
    validations:
      required: true

  - type: textarea
    id: environment_info
    attributes:
      label: Environment Information
      description: Provide information about your environment
      placeholder: |
        - Operating System: 
        - Python version: 
        - Toolkit version: 
        - Installation method: (pip, pipx, etc.)
        - Virtual environment: (yes/no)
      render: shell

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other relevant information about this vulnerability
      placeholder: |
        - Links to security advisories
        - Related vulnerability reports
        - Additional research or analysis
        - Timeline constraints

  - type: checkboxes
    id: disclosure_acknowledgment
    attributes:
      label: Responsible Disclosure
      description: Please acknowledge responsible disclosure practices
      options:
        - label: I understand this report will be public and visible to all users
          required: true
        - label: For critical vulnerabilities, I will use GitHub Security Advisories for private disclosure
          required: true
        - label: I have not included any exploit code that could cause harm
          required: true
        - label: I have provided enough information for the maintainers to understand and address the issue
          required: true
        - label: I have removed any sensitive information from my report
          required: true
